### ISSUE TITLE
after installation error

### ISSUE THREAD

**Issue by rapgithub** [mujahidi/acf-typography#1]
Warning: include_once(fields/acf-Typography-v5.php): failed to open stream: No such file or directory in /nfs//html/wp-content/plugins/acf-typography-master/acf-typography.php on line 77

Warning: include_once(): Failed opening 'fields/acf-Typography-v5.php' for inclusion (include_path='.:/acf-typography-master/acf-typography.php on line 77

**Comment by mujahidi** [comment]
@rapgithub Seems like you're trying to use the plugin with ACF version 5. The plugin currently doesn't support ACF 5. [It is only compatible with version 4](https://github.com/mujahidi/acf-typography#compatibility).

**Comment by mujahidi** [comment]
Hi @rapgithub,

Just wanted to let you know that acf-typography now supports ACF version 5 as  #well.

Regards
