### ISSUE TITLE
get font values from global options page

### ISSUE THREAD

**Issue by rrrrpppp** [mujahidi/acf-typography#11]
Hi @mujahidi,
your plugin looks very good. How can I get the font from options page?

To get a field from options page I can use the following as default (pls see https://www.advancedcustomfields.com/add-ons/options-page/):
`<p><?php the_field('field_name', 'option'); ?></p>`

This should return the value of a specific property:
`<?php get_typography_field( $selector, $property, [$post_id], [$format_value] ); ?>`

I'm not sure how to is it in my case. For example, I have a custom field called 'typofont', how can I get the font-family or size of 'typofont' from options page?

Do I need post_id in this case? $property should be 'font_family' or 'font_size'? Can you please explain how to get the values from 'typofont'?
`<?php get_typography_field( $typofont, $property, [$post_id], [$format_value] ); ?>`

Thank you and best regards
Robin

**Comment by mujahidi** [comment]
@rrrrpppp Similar to ACF, you would use `option` in place of the post ID.
```php
get_typography_field( 'typofont', 'font_family', 'option' );
```

**Comment by rrrrpppp** [comment]
@mujahidi thank you for the fast response! This works great for one single typography field. I just get empty rows if I try to use it in a repeater on options page:


```
<?php if( have_rows('fonts', 'option') ) : ?>
  <?php while( have_rows('fonts', 'option') ) : the_row(); ?>
    <?php the_typography_field( 'typofont', 'font_family', 'option' ); ?>');
  <?php endwhile; ?>
<?php endif; ?>
```

Do you have an advise for this case too?

**Comment by mujahidi** [comment]
@rrrrpppp For sub-fields, please use the sub-field functions;

```php
// Returns the value of a specific property from a sub field.
get_typography_sub_field( $selector, $property, [$format_value] );

// Displays the value of a specific property from a sub field.
the_typography_sub_field( $selector, $property, [$format_value] );
```

As per your example
```php
the_typography_sub_field( 'typofont', 'font_family' );
```

**Comment by rrrrpppp** [comment]
That's it! Great support, thank you.
