### ISSUE TITLE
Get_typography_field on options page doesn't work

### ISSUE THREAD

**Issue by coralie-noyer** [mujahidi/acf-typography#14]
Hello
I created a field who name is 'font1'. I show this field on Options page
I set a font-family on this field.
On index.php in my folder theme I had 
`$title = get_typography_field('font1', 'font-family', 'option); var_dump($title);`
The var_dump return `String(0)""`

How to do this ? 
Thanks

**Comment by mujahidi** [comment]
Hi @coralienyr 

I think you are using the incorrect parameter. The correct parameter for the font-family is `font_family`.

Try the following;
`$title = get_typography_field('font1', 'font_family', 'option);`
