### ISSUE TITLE
No Google Fonts

### ISSUE THREAD

**Issue by warudin** [mujahidi/acf-typography#15]
Hi,

I installed the plugin from wordpress.org (v3.0.0) and added a Google Fonts API-key to the settings. But I am not able to see Google-fonts in the 'Font Family' option. Do I need to do anything else to make the plugin work with Google Fonts?

I only see this:
![Schermafbeelding 2020-07-14 om 11 22 46](https://user-images.githubusercontent.com/1815847/87408853-60695880-c5c4-11ea-9514-16bbff8e5f5b.png)

**Comment by mujahidi** [comment]
@warudin Could be a permission issue for `google_fonts.json` file.
