### ISSUE TITLE
Bug with array_merge_recursive

### ISSUE THREAD

**Issue by landinr** [mujahidi/acf-typography#17]
We found that on posts that did not have ACF fields specified, fonts were appearing incorrectly. After review, we found that `array_merge_recursive` was returning a blank array. So this plugin will not work on any post that does not have ACF fields.

To address, we commented out `array_merge_recursive` and added the following:
`if(is_array($all_post_fields) and is_array($all_option_fields)) {
$all_fields = array_merge_recursive( $all_post_fields, $all_option_fields );
 } elseif(is_array($all_post_fields) ) {
 $all_fields = $all_post_fields ;
 } elseif(is_array($all_option_fields)) {
 $all_fields = $all_option_fields ;
 }`

Can this be addressed in a future version?

**Comment by mujahidi** [comment]
Hi @landinr, thank you for submitting the bug. I will review and release a new version with the fix. Thanks!

**Comment by landinr** [comment]
@mujahidi Thanks for taking a look at this! My development team alerted me to a few other issues, let me know if these should be added as separate threads:

1. When we have a page with just gutenberg blocks, then the font(s) defined in the blocks are NOT enqueued. This is because the code looks just for fields in the post and global options. It does not look for fields in the blocks.
2. Is it possible to have the Font Name field be optional? We are creating CSS styles so we don't want the font to be set. Would it be possible to add Null or Initial or No Font etc as the first value, and in code we can check for the value and adjust the code accordingly?

**Comment by mujahidi** [comment]
@landinr Can you open a new issue for the following issues, please? Thank you!

> @mujahidi Thanks for taking a look at this! My development team alerted me to a few other issues, let me know if these should be added as separate threads:
> 
> 1. When we have a page with just gutenberg blocks, then the font(s) defined in the blocks are NOT enqueued. This is because the code looks just for fields in the post and global options. It does not look for fields in the blocks.
> 2. Is it possible to have the Font Name field be optional? We are creating CSS styles so we don't want the font to be set. Would it be possible to add Null or Initial or No Font etc as the first value, and in code we can check for the value and adjust the code accordingly?

**Comment by landinr** [comment]
Issue 2 here: https://github.com/mujahidi/acf-typography/issues/18
Issue 3 here: https://github.com/mujahidi/acf-typography/issues/19

Thanks again @mujahidi !
