### ISSUE TITLE
Fonts defined in Gutenberg blocks not enqueued

### ISSUE THREAD

**Issue by landinr** [mujahidi/acf-typography#18]
When we have a page with just gutenberg blocks, then the font(s) defined in the blocks are NOT enqueued. This is because the code looks just for fields in the post and global options. It does not look for fields in the blocks.

**Comment by mujahidi** [comment]
@landinr Can you please share a screenshot of the block or steps to reproduce this?

**Comment by landinr** [comment]
Should not be a problem, asking our development team to take a look and will get you a screenshot ASAP.

**Comment by iajay** [comment]
Consider a simple custom ACF block with a typography field
Add this block to a page, set the font to a google font
No other fields on this page
Then the google font specified in the block wont enqueue 
The code in the functions.php is just looking for page fields and option fields
https://www.evernote.com/l/AAhuqyzlgEZCOZ8tlLCFeVTtpax8q-kPYpsB/image.png
But it does not look for fields in the blocks added to the page
Let me know if this is not clear
regards

**Comment by mujahidi** [comment]
Thanks @iajay . I will look into it.

**Comment by mujahidi** [comment]
@landinr @iajay Can you guys test https://github.com/mujahidi/acf-typography/commit/ed410919384b465fb3d44df744c4662d1920fe0a
