### ISSUE TITLE
Empty display fields while creating typography field results in Fatal error: Uncaught TypeError 

### ISSUE THREAD

**Issue by MuhammadFaizanHaidar** [mujahidi/acf-typography#21]
Error occurs in plugin/fields/acf-Typography-v5.php/line:383.
There should be a check to see if $field['display_properties'] is not empty.
Like this if( ! empty( $field['display_properties'] ) && sizeof($field['display_properties']) > 0){}
If a user selects no field to display in the typography metabox then it should not break.
I wanted to contribute but I was not able to play with branches.

**Comment by mujahidi** [comment]
Thanks @MuhammadFaizanHaidar This is already added to next patch I am working on.

**Comment by mujahidi** [comment]
Fixed in pull #22
